Paynetics.Task/Paynetics.Task/Controllers/XmlController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Paynetics.Services.Interfaces;

using Microsoft.AspNetCore.Authorization;

using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Paynetics.Web.Controllers
{
    public class XmlController : Controller
    {
        private readonly ISerializerService _serializerService;
        private readonly ITransactionService _transactionService;
        private readonly IExportService _exportService;

        public XmlController(ISerializerService serializerService, ITransactionService transactionService, IExportService exportService)
        {
            this._serializerService = serializerService;
            this._transactionService = transactionService;
            this._exportService = exportService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if(file != null)
            {
                var operation = this._serializerService.Serializer(file);

                if (operation.Transactions.Count() != 0)
                {
                    await _transactionService.CreateTransactionsAsync(operation.Transactions);
                }
            }

            return RedirectToAction("Index", "Transaction");
        }

        [HttpPost]
        public async Task<IActionResult> ExportCsv(DateTime date)
        {
            var transactions = await this._transactionService.GetAllTransactionsAsync(date);

            var file = new StringBuilder();

            if (transactions.Count() != 0)
            {
                file = this._exportService.Export(transactions);
            }

            return File(Encoding.UTF8.GetBytes(file.ToString()), "application/vnd.ms-excel", "Transactions.csv");
        }
    }
}

Paynetics.Task/Paynetics.Task/Views/Xml/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
}

<h2>Upload Xml File Here!</h2>
<form asp-controller="Xml" asp-action="Upload" enctype="multipart/form-data">
    <label for="myfile">Select a file:</label>
    <input type="file" id="file" name="file" />
    <button asp-controller="Xml" asp-action="Upload" class="btn btn-primary">Upload</button>
</form>
<br />
<br />
<br />
<br />
<h2>Export transactions in .csc file for current date!</h2>
<form asp-controller="Xml" asp-action="ExportCsv">
    <label for="start">Start date:</label>
    <input type="datetime-local" id="date" name="date" data-provide="datepicker" class="datepicker">
    <button asp-controller="Xml" asp-action="ExportCsv" class="btn btn-primary">CSV</button>
</form>

@*<script>
        var button = document.querySelectorAll('.btn').forEach(el =>
            el.addEventListener('click', function () {
                var loader = document.querySelector('.spinner-border');
                document.querySelectorAll('.datepicker').forEach(function (element) {
                    element.disabled = true;
                })

                var date = new Date();
                date = document.querySelector('#date').value;
                var url = this.getAttribute('data-export-csv-url');

                var data = new FormData();

                data.append('date', date);

                $.ajax({
                    url: url,
                    data: data,
                    dataType: "json",
                    type: "GET",
                    contentType: false,
                    processData: false,
                    traditional: true
                });

                document.querySelectorAll('.datepicker').forEach(function (element) {
                    element.disabled = false;
                });

                document.querySelectorAll('.button').forEach(function (button) {
                    button.disabled = false;
                });

            }, false));
</script>*@